service:
  name: ops-orchestrator
  host: 0.0.0.0
  port: 8003
logging:
  level: INFO
  json: true
deduplication:
  window_seconds: 300
  cache_size: 1000
approvals:
  enabled: true
  channel: slack
  webhook: ${APPROVAL_WEBHOOK}
rca_service:
  base_url: http://rca:8002
  timeout_seconds: 45
policy_repository:
  path: policies/remediation_policies.yaml
  refresh_interval_seconds: 120
observability:
  metrics_port: 9303
  histogram_buckets: [0.1, 0.25, 0.5, 1.0, 2.0, 5.0]
